### ISSUE TITLE
df, meta = pyreadstat.read_file_multiprocessing(pyreadstat.read_xport, file_path) results in exception. 

### ISSUE THREAD

**Issue by glageju** [Roche/pyreadstat#105]
Describe the issue
I am working on improving reading speed for '.xpt' file. I am using pyread.read_file_multiprocessing() method which seems to working with improved performance for '.sav' files and '.dta' files. For '.xpt' files it produces an exception:
`Exception: The number of rows of the file cannot be determined` 

To Reproduce
1. Use this method: df, meta = pyreadstat.read_file_multiprocessing(pyreadstat.read_xport, file_path)
2. file_path can be substituted for the file [here ](https://github.com/pandas-dev/pandas/blob/master/pandas/tests/io/sas/data/SSHSV1_A.xpt) which I used for this test.

Insight:
This error seems to causing on line #680 at [ _, meta = read_function(file_path, metadataonly=True)]( https://github.com/Roche/pyreadstat/blob/0c1c9d59f71a85746dd68757c9aa6a775dcd4eb7/pyreadstat/pyreadstat.pyx). With this, `meta.number_rows=None` is incorrect and causes the error above.

Expected behavior
I expect to get back **df, meta** values on above method as I would exactly get from df, meta = pyreadstat.read_xport(file_path).

Setup Information:
How did you install pyreadstat?: conda
Platform: linux
Python Version: 3.7.9
Python Distribution: Anaconda

**Comment by ofajardo** [comment]
Thanks for the precise report. As you mentioned the issue is coming from _, meta = read_function(file_path, metadataonly=True). The problem is that for XPORT files the C backend Readstat cannot extract the number of rows from the header of the file (looking at the xport specification from SAS it seems they just don't record that number there), therefore the number of rows of the file cannot be determined without fully reading it. 

For multiprocessing I need the precise number of rows to read in order to correctly partition the file. And as in this case I cannot get it I abort. 

The only workaround I can think of is I can introduce a new argument "num_rows" for read_file_multiprocessing where the user (you) will need to introduce manually what is the number of rows the file has. That means you will need to do a fist reading of the file with the slow process to determine the number of rows, and subsequent readings can be speeded up with multiprocessing. 

I didn't implemented that because if you already read the whole file with the slow process, why would you like to read it again faster? But I guess there could be use cases for that. The other reason is that this argument is a bit dangerous as if the number of rows is wrong other errors could arise. 

But anyway, if you think having num_rows would be useful for you, I can introduce it in the next version of pyreadstat. Other than that I am afraid not much can be done to solve this issue.

**Comment by glageju** [comment]
Unfortunate that XPORT file header doesn't have number of rows information.

For `meta.number_rows` it doesn't make sense to drag down performance for the sake of completion and I don't have a use case. However, for multiprocessing it would be helpful to indicate that XPORT files are not supported as for `sas_7bcat` in the [same method](https://github.com/Roche/pyreadstat/blob/0c1c9d59f71a85746dd68757c9aa6a775dcd4eb7/pyreadstat/pyreadstat.pyx#L674-L675).

**Comment by ofajardo** [comment]
Yes, I will include in the error message that Xport, sas7bcat and por files are not supported. That indeed will be more clear than the current error message.

**Comment by ofajardo** [comment]
I have done a new release 1.2.2 where now you have the argument num_rows that has to be equal or larger than the number of rows in the file. You have to determine this number yourself, either reading the file wihthout multiprocessing first, reading in the original application, or for example setting a very large number, if then the number of rows is less than your number, that means all rows were read, otherwise you have to repeat the operation until the number of rows is less than your number.
