### ISSUE TITLE
python 3.10

### ISSUE THREAD

**Issue by swuecho** [Roche/pyreadstat#151]
Please read the README, particularly the known limitations section!

Describe the issue
A clear and concise description of what the issue is.

```
	    import pyreadstat
	   .venv/lib/python3.10/site-packages/pyreadstat/__init__.py:17: in <module>	  
            from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
           ImportError: /app/.venv/lib/python3.10/site-packages/pyreadstat/pyreadstat.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyGen_Send
```

seems a compatibility issues.

Setup Information:
How did you install pyreadstat? pip 1.1.3
Platform (windows, macOS, linux, 32 or 64 bit) linux 64 (docker python 3.10.0)
Python Version
Python Distribution (System, plain python, Anaconda)
Using Virtualenv or condaenv? venv

**Comment by swuecho** [comment]
related

 https://github.com/MagicStack/uvloop/issues/417

**Comment by ofajardo** [comment]
thanks. My guess is that if the package is installed from source, having Cython installed, so that the sources are re-cythonized from scratch, then this particular error should be gone. 

I have not been able to try myself since right now creating a conda environment with python 3.10 fails, I have removed Docker Desktop from my laptop since it is not free anymore, and I also tried to produce wheels on azure and appveyor but those also fail. I guess I will wait a little bit until I can get it to work with a conda environment, that will make testing much easier for me.

**Comment by swuecho** [comment]
You are right. after pin cython to latest version and `pip install --no-cache-dir  pyreadstat --no-binary :all: ` the problem goes away.  Thanks.

**Comment by swuecho** [comment]
BTW. github codespace provide a convenient linux environment. 
![image](https://user-images.githubusercontent.com/666683/141147210-5670b954-46ce-45b4-8f4d-33c72735650c.png)

**Comment by ofajardo** [comment]
Great that it worked! In the meantime I managed to produce wheels on azure for linux and mac, which I uploaded to pypi. Windows is still failing since it is dependent on creating a conda environment with python 3.10, which still is problematic.

**Comment by ofajardo** [comment]
OK, windows wheels also succeed now and in pypi. 

Only thing left, for the next version eventually, is to force re-cythonization if the user is installing from source.

**Comment by ofajardo** [comment]
version 1.1.1 is out with wheels for python 3.10. Also setup.py has been changed so that it is always recythonized. This will make the process easier if installing from source.
