### ISSUE TITLE
sas7bdat datetime represented as float64 

### ISSUE THREAD

**Issue by vng510** [Roche/pyreadstat#171]
Hi,

Great package!  I'm reading in a sas7bdat file and noticed that datetime variables are represented as float64 in the datafame.

Original SAS Variable:  
  Value = 15JUL2006:00:00:00.000
  Format = DATETIME22.3
  Informat = DATETIME22.3
  Type = Numeric, Length = 8

 Dataframe: 
  Value = 1468540800
  Type = Float64

I tried multiple combinations of call but the result is the same:
df, meta = pyreadstat.read_sas7bdat('ae.sas7bdat')
df, meta = pyreadstat.read_sas7bdat('ae.sas7bdat', dates_as_pandas_datetime=True)
df, meta = pyreadstat.read_sas7bdat('ae.sas7bdat', disable_datetime_conversion =False)

The result of meta.original_variable_types is 'DATETIME22'.  Any help would be appreciated!

**Comment by ofajardo** [comment]
OK I have added DATETIME22 to the SAS formats pyreadstat should recognize as datetimes. Hopefully that should fix it (I think I don't need the .3 after the 22 as that is the width). I pushed the change to the dev branch. If you could compile and install from dev and confirm it is working it would be great. Otherwise the fix will be available with the next version and hopefully it will solve the issue.

**Comment by vng510** [comment]
Thanks for the update.  Just curious on how you are handling this.  I believe that DATE is calculated from days since 01JAN1960 and DATETIME is calculated from the number of seconds since 01JAN1960.  Perhaps I'm being naive but wouldn't a generic algorithm be to do the seconds delta for all DATETIME regardless of the variants (eg., datetime22.3, datetime16, datetime19, etc)?

**Comment by ofajardo** [comment]
the algorithm is generic for any date, datetime or time. But before applying the algorithm one has to decide in first place if it has to be applied, that means the C library gives you two pieces of information: first a double number, and second a string with the format. Then I have to look at the format and decide if I should transform it into a DATE, a DATETIME or a TIME. When I started with the library I was thinking naively that I just do a list with the possible formats for each category and check if the format is on the list. That works, the problem is of course that now I know the list is not static and have to keep adding things. I could try to set something like a regex to discover what it is the format, the thing is that there are all kind of funny formats (not easy ones like DATE, DATETIMEXX, etc) so it would be difficult to make a general rule.

**Comment by vng510** [comment]
Got it.  Thanks!  I tried to install DEV branch but it looks like it requires Pandas v1.20 or later.  The machine that I am on is Python 3.6 which works for the main branch.  I'll spin up a new instance and test the DEV next week.  I'll let you know.  Thanks again.

**Comment by vng510** [comment]
Confirmed the change works well on DEV.  Thanks.

**Comment by ofajardo** [comment]
Perfect! Thanks for the confirmation

**Comment by ofajardo** [comment]
solved in version 1.1.5

**Comment by ofajardo** [comment]
the next version will have two new arguments extra_date_formats and extra_datetime_formats where the user can add arbitrary formats to be parsed as date or datetime. This is a workaround solution while new formats are added, or for strange formats that cannot be converted to python date, datetime or time objects. See readme on dev.
