### ISSUE TITLE
Problem Saving Variables with pyreadstat.write_sav

### ISSUE THREAD

**Issue by sher-singh** [Roche/pyreadstat#204]
I am trying to merge 2 SPSS file into one SPSS but when I am saving file using pyreadstat.write_sav then all numeric values coming in decimal  in the output SPSS file.

df, meta = pyreadstat.read_sav('spss_file_name_1.sav', apply_value_formats=False, disable_datetime_conversion=True, user_missing=True)

df_2, meta_2 = pyreadstat.read_sav('spss_file_name_2.sav', apply_value_formats=False, disable_datetime_conversion=True, user_missing=True)

frames = [pd.DataFrame(df), pd.DataFrame(df_2)]
data_final = pd.concat(frames)

#used some variables from meta to keep labels, values and measures as per original SPSS file

pyreadstat.write_sav(data_final, "SPSS_Merged.sav", variable_measure=measures, column_labels=c_labels, variable_value_labels=variable_l)

**Comment by ofajardo** [comment]
As indicated in the issue template, please provide the sample files to reproduce the issue. If I cannot reproduce the issue, I cannot solve it.

**Comment by sher-singh** [comment]
Appreciate your prompt response.

[SPSS project files.zip](https://github.com/Roche/pyreadstat/files/9175112/SPSS.project.files.zip)

I have uploaded my python script file with 3 spss file including merged one. Merged file you can see decimal places changed in from source file and all values appearing in decimal.

**Comment by sher-singh** [comment]
> As indicated in the issue template, please provide the sample files to reproduce the issue. If I cannot reproduce the issue, I cannot solve it.

Hi Otto, do you have any solution for the problem that I have mentioned?

**Comment by ofajardo** [comment]
I will take a look at some point, and then it will take some more time until there is a new release. Stay tuned.

**Comment by ofajardo** [comment]
I have not had time to check your files or your code, but thinking about it:

1- Please provide the full information to reproduce. In your code example please share your definition of messures, c_labels, variable_I

2- You need to define the variable_formats, with 'integer' check carefully the Readme and the Module documenarion to thus respect. Probably this should be enough to solve the issue, because what you are describing is the expected behavior if you dont set the variable_formats. Try it and come back with a full reproducible example if still doesnt work. And as explained in the issue template... Please read the Readme carefully

**Comment by sher-singh** [comment]
thanks for your help, variable_format solves the problem here

**Comment by ofajardo** [comment]
Great! Glad to hear it is solved and thanks for the feedback!
