### ISSUE TITLE
Writing date formats

### ISSUE THREAD

**Issue by jttaggart** [Roche/pyreadstat#211]
When writing dates the original SPSS date format is lost.
All dates are saved as: dd-mmm-yyyy

run attached date_time.py on date_time.sav (attached).
saved_date_time.sav has different formatting.

Variable date variables format are saved as: dd-mmm-yyyy.
Variables:
dd_dot_mm_dot_yyyy
mm_dd_yyyy
dd_mmm_yyyy

Expected behavior
Retain original format.

Windows 10 64 bit
pyreadstat  Version1.2.0
Setup Information:
Installed with pip
Python 3.10.2
Using Virtualenv (Pycharm)

[date_time.zip](https://github.com/Roche/pyreadstat/files/10034713/date_time.zip)

**Comment by ofajardo** [comment]
It is not possible to automatically do what you are requesting, because when the data is read into pandas, pandas doesn't have (or need) the concept of date display format, therefore the original date format is unavoidably lost.

What you can do is to extract from the metadata the original variable formats (original_variable_types) you are interested in and give them to the write function using the variable_format argument. You can learn more in the Readme and Module documentation.

**Comment by ofajardo** [comment]
Something along these lines (not tested)

```
import re

import pandas as pd
import datetime
import pyreadstat

df_spss, meta = pyreadstat.read_sav("date_time.sav", user_missing=False)

pyreadstat.write_sav(df_spss, "saved_date_time.sav",
   variable_format=meta.original_variable_types)

print(df_spss)
```

Or you can extract from meta.original_variable_types only those variables you want to format

**Comment by jttaggart** [comment]
Hi Otto,,

 

I was playing around with this since I sent issue. I figured out what you suggested about 30 minutes ago. I have been trying to figure out for a day or so when this approach suddenly occurred to me.

 

I was about to send you an email when I got yours.

 

Thank you so much for looking into this.

 

Regards,

 

John

**Comment by ofajardo** [comment]
Awesome! Thanks for the feedback!
