### ISSUE TITLE
reading file in chunks.

### ISSUE THREAD

**Issue by MrJaatt** [Roche/pyreadstat#222]
![image_2023-03-23_233820378](https://user-images.githubusercontent.com/96114656/227305548-a7373608-cf9c-49c7-9976-cdd8a032b293.png)

The Code where I am getting this problem.
import pandas as pd
import time
import numpy as np
from pyreadstat import * 
import os , threading , multiprocessing
from multiprocesspandas import applyparallel
import shutil , subprocess

if __name__ == "__main__":
    reader = pyreadstat.read_file_in_chunks(pyreadstat.read_sav, fpath, chunksize= 20000, multiprocess=True, num_processes=4)
    print(type(reader))
    pd_datframe = pd.DataFrame()
    for df in reader:
            print(f"df:{type(df)}")

ERROR:

File "pyreadstat\pyreadstat.pyx", line 750, in pyreadstat.pyreadstat.read_file_multiprocessing        
Exception: The number of rows of the file cannot be determined from the file's metadata

used pip to install pyreadstat.

**Comment by MrJaatt** [comment]
![image_2023-03-24_002543340](https://user-images.githubusercontent.com/96114656/227319514-01bf34b6-9e8f-4ad8-a790-42224cc1328d.png)

**Comment by ofajardo** [comment]
Very similar to #109 . Most likely your spss file was not generated by SPSS but by some other application like Qualtrics, where the number of rows is not registered in the header of the file. Nothing can be done to solve that.

Only if you are positive that the file was written by SPSS , attach the file for inspection, or try to see if you see the number of rows using a binary file viewer, there you will also see which application wrote the file.

**Comment by MrJaatt** [comment]
Thank  you for writing back. 
yes the file was not written by IBM spss. the file was written by Qualtrics..
Is there any way to check if  number of rows is  registered in the header of the file?
Thanks!!

**Comment by ofajardo** [comment]
when you use read in chunks, the program needs to know the number of rows in advance before reading the file, if it is not available from the header, like in the case of Qualtrics it cannot be used that is why you get the error. When you read using the normal slow way, the program first reads all the data and then calculate the number of rows from the pandas data frame (not anymore from the header), that is why you get it in the metadata container, but that doesn't help for read in chunks.

In order to see the number of rows in the header, take any spss written sav file, where you know the number of rows, then open the file in any binary text viewer, there are many online like [this](https://hexed.it/), or you can download and install any free one for your platform. Then, find at the very beginning of the file a field that has the number you know is the number of rows. Then open the Qualtrix file in the binary editor and look at the location you have identified previously. You will see a -1 which means the number of rows is not registered.

**Comment by MrJaatt** [comment]
Thanks for the wonderful explanation and for the link as well.

this is what I saw there.
![Screenshot 2023-03-24 182006](https://user-images.githubusercontent.com/96114656/227526069-3d885929-5472-4db0-ac20-aaaa7901fd31.png)

**Comment by ofajardo** [comment]
It is probably the address 0x00000050 , in the first screenshot, you see there is on the top right a field go to ... you can write the address there, and then on the left panel see what number is in there. In the first screenshot you have a Qualtrix file, you see FF, which means -1 (which means unknown number of rows), in the second screenshot SPSS file, you see a 5, which is the number of rows for this file. 

![image](https://user-images.githubusercontent.com/17498727/227537031-2e8aeead-c379-4951-ba13-7e3fb31ec086.png)

![image](https://user-images.githubusercontent.com/17498727/227537606-d994aa86-529c-44e5-b772-091e31a26cca.png)

**Comment by MrJaatt** [comment]
wow, this is quite complicated 🤔 😊. However yes you are 100% correct on this. 

Thank you so much for your time!!

Have a great day ahead!!

**Comment by ofajardo** [comment]
I have done a new release 1.2.2 where now you have the argument num_rows that has to be equal or larger than the number of rows in the file. You have to determine this number yourself, either reading the file wihthout multiprocessing first, reading in the original application, or for example setting a very large number, if then the number of rows is less than your number, that means all rows were read, otherwise you have to repeat the operation until the number of rows is less than your number.
