### ISSUE TITLE
Original variable types NULL, though data types are present in SAS

### ISSUE THREAD

**Issue by katy-sadowski** [Roche/pyreadstat#223]
Describe the issue
I'm reading in a .sas7bdat file (attached here; it's fake clinical trial data) using `read_sas7bdat`.  When I print out the original variable types, they all show as `'NULL'`.  However, I checked with a SAS user on my team and she shared this screenshot of what she sees for the column types in SAS:

![Screen Shot 2023-03-24 at 10 04 21 AM](https://user-images.githubusercontent.com/38965545/227664457-eebfe973-35c3-4e04-8380-7e055e2c1727.png)

Either I am doing something wrong, or the file is corrupted, or maybe those types she sees in SAS != what's parsed out for original_variable_type?  

To Reproduce
Code:

```
import pyreadstat
df, meta = pyreadstat.read_sas7bdat('lb.sas7bdat')
print(meta.original_variable_types)
```

Output:

```
{'STUDYID': 'NULL', 'DOMAIN': 'NULL', 'USUBJID': 'NULL', 'LBSEQ': 'NULL', 'LBTESTCD': 'NULL', 'LBTEST': 'NULL', 'LBCAT': 'NULL', 'LBORRES': 'NULL', 'LBORRESU': 'NULL', 'LBORNRLO': 'NULL', 'LBORNRHI': 'NULL', 'LBSTRESC': 'NULL', 'LBSTRESN': 'NULL', 'LBSTRESU': 'NULL', 'LBSTNRLO': 'NULL', 'LBSTNRHI': 'NULL', 'LBNRIND': 'NULL', 'LBBLFL': 'NULL', 'VISITNUM': 'NULL', 'VISIT': 'NULL', 'VISITDY': 'NULL', 'LBDTC': 'NULL', 'LBDY': 'NULL'}
```

File example

[lb.sas7bdat.zip](https://github.com/Roche/pyreadstat/files/11067392/lb.sas7bdat.zip)

Expected behavior
I'd expect the types listed in SAS to show up as the original types in `original_variable_types`. 

Setup Information:
How did you install pyreadstat? pip
Platform macOS
Python Version 3.9
Python Distribution Plain python
Using Virtualenv or condaenv? no

**Comment by ofajardo** [comment]
There is a small confusion (because how I named original_variable_types) between data types and data formats. SAS has only two data types: char and number; those are translated to string and float in python (in pandas the columns will be object for string and float64). In your case if you look at the data types you get in your pandas data frame you can infer what type they had in SAS. Another way is to look at meta.readstat_variable_types where you will get either 'string' or 'double', double meaning a number. 

What original_variable_types really gives you is the format. SAS has plenty of formats and what it does is how to display a given number. For example, dates are just numbers that are displayed with a date format. You can adjust to display decimal points or not, how many decimals, etc. 

For example in this dataset, in SAS I am checking the variable mydate and it says the datatype is Numeric and the format is YYMMDD10. 

![image](https://user-images.githubusercontent.com/17498727/227705704-b5b51902-86fa-4ad1-84e0-2fd7f60a1560.png)

In your case however, your variables do not have any format, see screenshot. That is why you get NULL in the original_variable_types. If you want to get something there, you would need to go to SAS and set the format. If you don't SAS simply displays a default format for numbers and strings. But if you just need to know if they are either char or numeric, you can discover that very easily as I mentioned before. 

![image](https://user-images.githubusercontent.com/17498727/227705792-38a9c15e-bdd3-4ad9-8446-737e286b890a.png)

Nothing to be done as everything looks as expected.

**Comment by katy-sadowski** [comment]
Thanks so much for the helpful & thorough explanation!

**Comment by ofajardo** [comment]
welcome!

**Comment by katy-sadowski** [comment]
Hi there!  I have a follow-up question for you about this 😃 In SAS, some of the variables in this dataset appear as integers (for example, LBSEQ which is in your screenshot).  But since we're missing value formats in this file and all numbers get "double" format in the dataframe, these columns' values get a .0 appended to them.  If there were value formats in this file, and those formats specified these integer columns to be integers, would pyreadstat pick up on that and cast them as integers in the dataframe?

I can't completely tell if this will occur since the documentation states for `readstat_variable_types`: "In SAS and SPSS variables will be either double (numeric in the original app) or string (character)."

Thanks in advance!

**Comment by ofajardo** [comment]
Hi. No, Pyreadstat would not convert them to integers, they will allways appear as float (because in SAS they are double) and it is up to the user to do further transformations based on the formats, as in this case transforming them to integer. The only format based transformations that Pyreadstat does automatically are for dates, datetimes and times.

**Comment by katy-sadowski** [comment]
OK thank you very much for confirming!

**Comment by katy-sadowski** [comment]
Hi again!  I actually have one more question on this topic.  For these columns which appear as integers in SAS but get a .0 appended in the pyreadstat dataframe, I've actually observed that when reading in the same file in R using [haven](https://github.com/tidyverse/haven), the values appear as integers in the R dataframe.  

In the SAS [docs](https://go.documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/leforinforref/p1fum54c93f8r0n1wrs5mrb05nzi.htm) it also seems to imply that SAS is aware of integer vs float under the hood, even when a value format is not specified.  When describing the BESTw data format (which is used by default if no format is specified), it says `Integers are written without decimals`. 

It would seem to me that the correct behavior for pyreadstat would be to read in integer columns as integers rather than converting them to double.  But maybe I'm missing something here (perhaps Haven is making an assumption it shouldn't be?).  Let me know what you think; thanks!

**Comment by ofajardo** [comment]
hi, thanks for the question, I think it is a fair one. 

In SAS there is only one numeric type with decimals under the hood. This is known because in the sas7bdat files there is only one data type for numeric (and not 2 or more). However how that number is shown to the user in the application can be adjusted with the format. For example you could have a value of 3.5 but choose to show only 3 in the application Since in python there is not such dichotomy between what is the real value under the hood, and what is displayed, you have to choose either to show the real value, or to change the data to try to match what is displayed in the foreign application. While both are correct, and each has its merits, I think it is safer to give back to the user the real value and let her make the decision if she wants to change it later. The reason is that particularly with formats like BEST, where SAS has an algorithm to choose what is the best display (to guess if it is a decimal or integer in this case), we can never be sure that we have fully replicated their algorithm, and once we change the original data, there is no more possibility to go back for the user. I know that R is very prone to do decisions in behalf of the user, but I don't like that too much, for example in this case in R integers are 32 bits, meaning the maximum possible value is 2,147,483,647 ... what if the original value is larger? it gets truncated! (maybe they check if it is larger and in that case they convert to R numeric?, no idea). Exploring all edge cases would take time and it has to be also adapted for SPSS and STATA since pyreadstat supports those, adding more time invested.

In the case of dates, I do change the original data, because these are difficult to deal with, and even if that is much clearer than the BEST case, still new formats appear and disappear with each version of SAS, changes are needed, etc, adding more maintenance work. And remember pyreadstat reads not only SAS but also SPSS and STATA, multiplying the maintenance burden by 3. 

Another reason not to do such a change lightly is stability. I know that in the R world they are very trigger happy doing changes, but since pyreadstat is used by data engineering teams, where stability is important: if you write a data pipeline it has to work without changes for years, and for that reason is important that the underlying packages do not change too much. 

I would suggest that you write a function wrapping read_sas7bdat and there you can do the conversion to integer for the formats you know work for your data. Having said that, I will keep an eye on this, and also ask the engineers how do they deal with this issue.

**Comment by katy-sadowski** [comment]
Thanks for your reply!  This all makes sense to me, I appreciate the detailed explanation.  

I ran some tests in R vs Python/pandas.  Assuming you're correct about SAS storing everything as decimals under the hood, I think I can explain why Haven shows these columns as integers, and infer why SAS does the same:

**pandas**
```
>>> df = pandas.DataFrame({'Numbers': [1,2,3,4,5]})
>>> print(df)
   Numbers
0        1
1        2
2        3
3        4
4        5
>>> print(df.dtypes)
Numbers    int64
dtype: object
>>> df = pandas.DataFrame({'Numbers': [1.1,2,3,4,5]})
>>> print(df)
   Numbers
0      1.1
1      2.0
2      3.0
3      4.0
4      5.0
>>> print(df.dtypes)
Numbers    float64
dtype: object
>>> df = pandas.DataFrame({'Numbers': [1.0,2.0,3.0,4.0,5.0]})
>>> print(df)
   Numbers
0      1.0
1      2.0
2      3.0
3      4.0
4      5.0
>>> print(df.dtypes)
Numbers    float64
dtype: object
```

**R**
```
> df <- data.frame('Numbers' = c(1,2,3,4,5))
> print(df)
  Numbers
1       1
2       2
3       3
4       4
5       5
> typeof(df$Numbers)
[1] "double"
> df <- data.frame('Numbers' = c(1.1,2,3,4,5))
> print(df)
  Numbers
1     1.1
2     2.0
3     3.0
4     4.0
5     5.0
> typeof(df$Numbers)
[1] "double"
> df <- data.frame('Numbers' = c(1.0,2.0,3.0,4.0,5.0))
> print(df)
  Numbers
1       1
2       2
3       3
4       4
5       5
> typeof(df$Numbers)
[1] "double"
```

Looks like if all the values inserted into the R df have `.0` at the end, it'll get trimmed from the display (forgive me if the above was a no brainer....but today I learned 🙃 ).  This would definitely explain the issue I'm seeing in Haven vs pyreadstat. And it's plausible SAS does something similar with its "BEST" format.

**Comment by ofajardo** [comment]
Ah interesting, I didn't know either that R trins the decimals automatically, yes I guess that explains it.
