### ISSUE TITLE
support reading integers as integers in read_sav

### ISSUE THREAD

**Issue by ME-researchgroup** [Roche/pyreadstat#231]
First of all, thank you for this library!

Pyreadstat transforms integers to float64 with `read_sav` . This even happens the column is labelled as "nominal", the values are mapped to labels, and decimals set to 0 in SPSS. 

To Reproduce
```
import pyreadstat

df, meta = pyreadstat.read_sav("pyreadstat_issue.sav")
print(df)
```

File example
[pyreadstat_issue.zip](https://github.com/Roche/pyreadstat/files/12003763/pyreadstat_issue.zip)

Expected behavior
I would expect the column in the DataFrame to be of dtype int and would expect the code example to print
```
   variable
0          0
1          1
```

Setup Information:
- installed using pip
- on windows
- with plain python 3.10.4
- in a virtualenv

**Comment by ofajardo** [comment]
hi thanks for your proposal. I understand it and see that it would be a correct behaviour of the application. However, I consider the current behaviour to be also correct and be in addition better for maintainability. 

SPSS has only two data types: strings (character) and number, which is always a float/double, i.e. it has a decimal point. It definitely does not have an integer type. On top of that it has display choices, where you can adjust the width of how many decimal and non-decimal places should be displayed. In your file, if you inspect meta.original_variable_types you will see a 'F8.0', meaning it should display 8 non decimal figures and 0 non-decimals, that is why you see it displayed as an integer, while in fact it is not an integer underneath. There are many of these display possibilities, as apparently you can adjust both parts independently. 

In python, or in pandas, we do not have the display layer. That means you have to choose to display either the true values, which for SPSS are always floats with decimals (current behaviour) or to change the datatype so that it matches the display you are expecting (your proposed behaviour). I definitely choose the first option, first because once you change the datatype there is no way back, while if you leave the original data type, the user can always change it later; second because maintaining a these data type changes is a lot of work, as I have experienced in the only case where I am supporting it: dates and datetime, just because working with the actual numbers would be too annoying. As mentioned before there is potentially too many of these display options to care about (for example one could start rounding the floats to match the SPSS format etc.) to be practical to be maintained on my side. In addition I have heard different opinions on how these changes should be applied, to make me believe it depends on your use case and application wether you would like to apply the or not. 

What you can do, easily, is to read from the metadata object this field original_variable_types and do the changes you consider better for your project yourself, as for example transforming these columns with 'F8.0' to integers. You can also look at meta.variable_measure for the 'nominal' if that helps with your decision.

**Comment by ofajardo** [comment]
thanks for the understanding and the feedback! appreciated.
