### ISSUE TITLE
New feature proposal: Read Creation time and modified time of SAS7BDAT file

### ISSUE THREAD

**Issue by SInginc** [Roche/pyreadstat#240]
Dear `pyreadstat` developer,

Thank you for making this awsome Python package!

While using `pyreadstat` to read SAS7BDAT, I found below issues that I would like to address:

1. `meta` object returned by `read_sas7bdat` doesn't include the creation time and modified time of the SAS7BDAT file. The retionale of getting these two timestamps is that a SAS7BDAT file would have a different creation/modified timestamp in its metadata compared to the timestamp read by OS. In SAS, this internal timestamp could be obtained by `PROC CONTENT`.

2. When a SAS7BDAT dataset contains variable label encoded in encoding other than utf-8, there will be a error

My proposal regarding to above unfulfilled needs is:

1. Add creation/modified time to the meta class's attributes. `ReadStat` already has functions called `readstat_get_creation_time` ([here](https://github.com/Roche/pyreadstat/blob/f25fa75a72dbd89a967860e864981973038f09ee/src/readstat_metadata.c#L11)) and `readstat_get_modified_time` ([here](https://github.com/Roche/pyreadstat/blob/f25fa75a72dbd89a967860e864981973038f09ee/src/readstat_metadata.c#L11)) to get the creation/modified time of the file, but it seemed that these two functions were not exposed in `pyreadstat`. 

2.  When reading the label of a variable [here](https://github.com/Roche/pyreadstat/blob/master/pyreadstat/_readstat_parser.pyx#L478), maybe we can read it in `bytes` instead of `str`? Because it seems that in Python3, Python will encode `var_label` in utf-8 when it is casted to `str` and there will be an error when the label is no encoded in utf-8.

I have forked the repo and commit the changes [here](https://github.com/SInginc/pyreadstat/commit/6cb3cd71c68f2cdfef61dbb96784e1bfaa0af788) for you kind review. But I failed to compile the code in my environment. Would you mind sharing which version of Cython and C I should use to complie?

Thank you!
Jack

**Comment by ofajardo** [comment]
Thanks for the proposal. I had a quick look only and I think in general it looks good. Couple of things:

* Please make a pull request from the dev branch of this repo to your fork to update your code. In the last release I introduced compatibility with cython >= 3.0.0 while previous version of cython are no longer supported. You definitely want to work on top of that and not the outdated code you currently have. Try to compile again then to see if it works.

* creation/modification time: I think you are exposing it in the meta object as an integer? it should be a python date or datetime object instead, just convert it appropiatetly. 

* labels: I don't like the labels to suddenly become bytes if they have been str so far, that is a breaking change. I was not aware of that error, I guess that is something that Readstat should correct rather than pyreadstat exposing them as bytes. Readstat normally should convert everything to utf-8 automatically ... are you sure of this? can you provide an example?. Sometimes it was happening that Readstat was failing to read the proper encoding, but then supplying the encoding while reading the file solved it. Not sure if that would help in this case.

As an alternative if you find the way to try to convert them to an utf-8 str and if it fails then leave them as bytes, that would be acceptable if everything else fails.

Thanks!
Otto

**Comment by dostiep** [comment]
Hello,
I'm also interested in having creation and modification date/time but also for XPT file format.

Do you think this could be implemented as well? 

Any timelines on when those could be implemented?

Thanks

Pierre

**Comment by SInginc** [comment]
Hi @ofajardo ,

Regarding adding creation/modification time to metadata object, I created a [PR](https://github.com/Roche/pyreadstat/pull/242) for dev branch. 

As for reading column label not encoded in utf-8, I am still looking for public datasets as examples. But I can confirm that when the labels are in encodings like Shift-jis, there would be an error thrown with reading my internal datasests. So I didn't include this update in the PR.

Thanks!
Jack

**Comment by ofajardo** [comment]
it works nicely, great stuff! thanks! Only minor modification I did is to have those dates as python datetime objects, so the user has flexibility to format them as a string or let them as datetime objects to do time calculations or upload to a database etc. Added tests and documentation. I will make a release soon with these updates, for now on dev branch.

**Comment by ofajardo** [comment]
I have released version 1.2.4 with the proposed change. Testing it in two different machines it worked well. For some strange reason my unitests failed in some machines on azure (but some others were working). As it is so painful to debug stuff on azure, I have commented out those tests for now. Let's observe if anybody reports any errors with the dates.

If you could, it would be nice if you could try it and report if it is working fine for you.

**Comment by SInginc** [comment]
> I have released version 1.2.4 with the proposed change. Testing it in two different machines it worked well. For some strange reason my unitests failed in some machines on azure (but some others were working). As it is so painful to debug stuff on azure, I have commented out those tests for now. Let's observe if anybody reports any errors with the dates.
> 
> If you could, it would be nice if you could try it and report if it is working fine for you. 

Thank you! Sure I would test reading the dates (might mainly focus on SAS files).
