### ISSUE TITLE
File did not contain the expected number of rows

### ISSUE THREAD

**Issue by TcaManager** [Roche/pyreadstat#3]
`ReadstatError: File did not contain the expected number of rows`

Hi, I get this error when I try to read a file. Same file opens perfectly with sas7bdat package.
How is it possible?
Thanks for your help.

**Comment by ofajardo** [comment]
The fact that it is a ReadstatError means that the error is coming from the C code in the readstat library rather than my python wrapper. It would be good to confirm that by trying to read that file using readstat command line tool directly (https://github.com/WizardMac/ReadStat). IF it raises the same error, then it confirms it is a bug in readstat and the best would be to file the bug in their repo. If it does not raise the same error, then it could be that the bug is in my code and I should look at it (in which case I would need a copy of the file, otherwise it would be impossible to debug)
Does it sound like something you could do?

**Comment by ofajardo** [comment]
Maybe the sas file you are looking at is compressed?
It may be related to this: https://github.com/tidyverse/haven/issues/38

**Comment by ofajardo** [comment]
Most likely it is a binary compressed file, which sas7bdat can handle but readstat cannot.

Closed after 1 month of inactivity. Please reopen the ticket if necessary.
