### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by goolig** [Roche/pyreadstat#33]
ImportError: DLL load failed: The specified module could not be found.

For this command:
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat

Using windows 10 and python 3.6.
installed using pip install.

Thanks for this great package.

**Comment by ofajardo** [comment]
hi

pyreadstat depends on a few dynamic linked libraries (.dll files) and for some reason your system cannot find them. In order to solve this I will need your collaboration to find out which one is the missing one, because as you see windows is so nice that does not tell us which dll is the missing one. 

I supply these two dlls in the python wheel. These should be copied to the directory of your python installation (using vanilla python or anaconda/miniconda by the way?). Can you check if they are there?:

libiconv-2.dll
zlib1.dll

If they are there, then check if this directory is in the windows path and if not add it. If they are not it would be interesting to know why not, but workaround is to copy them from this repository from the folder win_lib/64bit and paste them there. If they are there and the directory is in the path and still not working, then please download [this program](https://github.com/lucasg/Dependencies) run it, and open the file pyreadstat.cp36-win_amd64.pyd in the folder Lib/site-packages-pyreadstat under your python installation. It will show you the dll dependencies and which one is the missing one. Paste here a screenshot of the result. 

In addition there are other dlls that should be present: 
python36.dll -> in your python installation directory

and these in these from the system: C:\Windows\System32
    KERNEL32.dll
    msvcrt.dll
    USER32.dll

All of them should be present and reachable. 

Let me know how it goes.

**Comment by goolig** [comment]
Both DLL files are in place - libiconv-2.dll, zlib1.dll. I have added the pytho path to PATH just to make sure, still not working. Here is the screenshot:
![image](https://user-images.githubusercontent.com/11397146/61184351-6812bc00-a655-11e9-839a-ffbdabb5f74c.png)

I'm using Anaconda...

The other DLLS you mentioned are in place.
Thanks

**Comment by ofajardo** [comment]
so I see that you have installed pyreadstat in a conda enviroment. Can you try to add the path to the conda environment to the python path? because in your case the dlls are there and not in the python installation directory. I mean C:\Users\Administrator\Anaconda3\envs\py36.

**Comment by goolig** [comment]
The problem is solved, your first solution was good - adding python path to env PATH, it was my fault (working with Pycharm had to close all windows, not just one for the env variable to update).
I guess the env variable should be applied during the installation. 
Thanks for your help. 

PS:
conda install pyreadstat

Gives:
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pyreadstat

**Comment by ofajardo** [comment]
great to hear is good. Installing with conda is described in the readme:

```
conda install -c conda-forge pyreadstat 
```

**Comment by ernstbloch20** [comment]
Hello, 

I have a similar issue. I tried what you suggested in this thread. But, it didn't work for me. I'm using Pycharm. In Pycharm, I installed 'pyreadstat' and it successfully did. And, in the pycharm, I tried to import by import pyreadstat. But, I got an error message in return:

import pyreadstat
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\zeony\PycharmProjects\venv\lib\site-packages\pyreadstat\__init__.py", line 17, in <module>
    from .pyreadstat import read_sas7bdat, read_xport, read_dta, read_sav, read_por, read_sas7bcat
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: DLL load failed: The specified module could not be found.

I don't know how I can solve this issue. 
Maybe I didn't get what you said ("because in your case the dlls are there and not in the python installation directory. I mean C:\Users\Administrator\Anaconda3\envs\py36".). 

Thank you so much in advance!!

**Comment by ofajardo** [comment]
Basically you have to locate where the dlls are and add that folder to the Windows PATH variable.

**Comment by ernstbloch20** [comment]
It worked! thanks! Just in case for others having a similar issue, what I did is this:

1. find the folder of pyreadstat.
2. copy the whole directory of that folder (e.g., "C:\Users\me\PycharmProjects\venv\Lib\site-packages\pyreadstat
3. go to Environment Variables and find "PATH".
4. Edit Path and include the directory (the location) that I just found. 

And it worked!

Thank you so much!!!!

**Comment by ofajardo** [comment]
On version 0.3.1 windows dlls are now copied into the package folder, that should make fixing the PATH unnecessary.

**Comment by ofajardo** [comment]
version 1.1.8 does a static compilation with msvc, so no more dll files to be copied etc, that hopefully should solve these issues.
