### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Perecles-Py** [Roche/pyreadstat#35]
**Describe the issue**
While attempting to install pyreadstat using pip in command line, the following error was generated:

> ERROR: Command errored out with exit status 1:
>      command: 'C:\Users\jwelch\AppData\Local\Programs\Python\Python37-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jwelch\\AppData\\Local\\Temp\\pip-install-jcs8gadj\\pyreadstat\\setup.py'"'"'; __file__='"'"'C:\\Users\\jwelch\\AppData\\Local\\Temp\\pip-install-jcs8gadj\\pyreadstat\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
>          cwd: C:\Users\jwelch\AppData\Local\Temp\pip-install-jcs8gadj\pyreadstat\
>     Complete output (1 lines):
>     It seems you are using windows 32bit, you will need to find zlib1.dll and libiconv-2.dll from mingw 32 bits, (It is usually in the bin folder of mingw32 if you are using msys) put it in the folder win_libs/32bit, remove the sys.exit in the setup.py file and try again. Or maybe the dlls in the 64 bit folder work for 32 bit as well ... couldn't try as I don't have access toa 32 bit machine. Sorry!
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**To Reproduce**

While running command prompt as an Admin
- python -m pip install pyreadstat

**Expected behavior**
Successful installation of the package

**Setup Information:**
How did you install pyreadstat? Attempted through pip version 19.2.1
Platform Windows 10 x64
Python Version 3.7
Python Distribution System
Using Virtualenv or condaenv? Default environment

**Comment by ofajardo** [comment]
You are using windows 64 bit, but python 3.7 32 bit. 
Is it an option to use python 64 bit? that would immediately solve the issue.
Otherwise currently pyreadstat for windows is compiled only for 64 bit as I don't have a 32 bit machine to test that it really works. Something you could try is to install manually: download the wheel, unzip it, copy the pyd files to a subfolder pyreadstat in site-packages and the dll files on the python root folder (C:\Users\jwelch\AppData\Local\Programs\Python\Python37-32). IF that works then I can remove that error from setup.py so that it can be installed with pip directly. If it does not work then it means it needs recompilation for 32 bit.

**Comment by ofajardo** [comment]
Another workaround: install WSL for windows and install there. Pyreadstat us available for 32 and 64 bit for linux

**Comment by ofajardo** [comment]
@Perecles-Py I have uploaded 32 bit wheels for Python 3.5, 3.6 and 3.7 to PyPI. Now you should be able to install with pip. Let me know if it works and feel free to re-open the issue if something is not working.
