### ISSUE TITLE
 ModuleNotFoundError: No module named 'pyreadstat._readstat_parser'; 'pyreadstat' is not a package

### ISSUE THREAD

**Issue by charliegreene9** [Roche/pyreadstat#44]
Hi, I am having a problem upon importing pyreadstat.

I am using Jupyter Notebook 5.7.4 with Python 3.7.1 from Anaconda 3.x on 64bit Windows 10. I pip installed pyreadstat within Jupyter Notebooks.

Upon typing "`import pyreadstat`" it produces the error \

`pyreadstat\_readstat_parser.pxd in init `pyreadstat.pyreadstat()`

`ModuleNotFoundError:` No module named 'pyreadstat._readstat_parser'; 'pyreadstat' is not a` `package`

Previously this package worked great and I am a big fan of it how well it works. I was attempting to use it when creating a Tkinter stand alone exe and it failed to include it in the creation. This was due to my needing to use Python 3.x not a form of IPython or Anaconda to execute this pyinstaller creation. After pip installing there it claimed this error, after some checking and editing nothing would help it work and it has not worked since. Any ideas on how to repair this? I have deleted the files and reinstalled and uninstalled and reinstalled in the clean Python as well.

**Comment by ofajardo** [comment]
very strange ...

Can you first of all in your jupyter notebook do:

```
import sys
print(sys.executable)
```
this will give you the path to the python interpreter you are using. Then go to that folder and look for the pyreadstat package, in Lib\site-packages\pyreadstat. What do you see in there as content?

I have:

```
__init__.py  
pyreadstat.cp36-win_amd64.pyd
_readstat_writer.cp36-win_amd64.pyd
_readstat_parser.cp36-win_amd64.pyd
```

**Comment by charliegreene9** [comment]
> very strange ...
> 
> Can you first of all in your jupyter notebook do:
> 
> ```
> import sys
> print(sys.executable)
> ```
> 
> this will give you the path to the python interpreter you are using. Then go to that folder and look for the pyreadstat package, in Lib\site-packages\pyreadstat. What do you see in there as content?
> 
> I have:
> 
> ```
> __init__.py  
> pyreadstat.cp36-win_amd64.pyd
> _readstat_writer.cp36-win_amd64.pyd
> _readstat_parser.cp36-win_amd64.pyd
> ```

Thanks for the fast response! 

Sure, I have

`__pycache__
__init__.py
_readstat_parser.cp37-win_amd64.pyd
_readstat_writer.cp37-win_amd64.pyd
pyreadstat.cp37-win_amd64.pyd`

inside __pycache__ is

`__initi__.cpython-37.pyc`

**Comment by ofajardo** [comment]
Hmm looks good.

What happens if you open python from command line (no ipython, no jupyter etc) and try to import pyreadstat? Works or error?

**Comment by charliegreene9** [comment]
It looks like the same error still, 

``Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyreadstat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyreadstat\_readstat_parser.pxd", line 42, in init pyreadstat.pyreadstat
ModuleNotFoundError: No module named 'pyreadstat._readstat_parser'; 'pyreadstat' is not a package``

**Comment by ofajardo** [comment]
OK I think that the explanation is that you have somewhere either a file called pyreadstat.py that is interfering with the pyreadstat package , see this: 

https://stackoverflow.com/questions/31279446/import-error-no-module-named-xxxx

It also could be that you have a broken package somewhere else. In order to know where it is trying to import pyreadstat or what it thinks pyreadstat is, in the command line, start python in verbose mode:

```
python -v
```
and then try to import pyreadstat. It will print a lot of things among them from where it is importing pyreadstat, for sure it is not from site-packages.

Let me know.

**Comment by charliegreene9** [comment]
I tested both and found no pyreadstat.py, but I did find this:

```>>> import pyreadstat
# extension module 'pyreadstat' loaded from 'C:\\Users\\charlie.greene\\pyreadstat.cp37-win_amd64.pyd'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1050, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "pyreadstat\_readstat_parser.pxd", line 42, in init pyreadstat.pyreadstat
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pyreadstat._readstat_parser'; 'pyreadstat' is not a package
>>>```


I deleted the file and it seems to work fine in all the test so far. I guess I placed it there when investigating the initial problem? Thanks for the help Otto! 

I will see if Tkinter still experiences the same problem importing it or not, if you don't mind I will keep the issue open until I test that. Otherwise I am happy open it as a new issue if it has more problems in Tkinter or message you about it. 

Cheers!

**Comment by ofajardo** [comment]
glad to hear it's solved now. Please open another issue if needed as it sounds as a different thing. Closing this now.

Regarding creating exe files, I have never used TKinter, and it has been long since last time I did it, but I remember when using cx_freeze or .... (can't remember the other one) that some times it was tricky to get it to include everything and you have to start tweaking in order to get it. Something along these lines: 

https://stackoverflow.com/questions/43059408/how-to-include-tkinter-when-using-cx-freeze-to-convert-script-to-exe
