### ISSUE TITLE
pip install version 0.3.3 fails. unistd.h missing/ error C1083

### ISSUE THREAD

**Issue by finnkr539** [Roche/pyreadstat#61]
## Describe the issue
```pip install pyreadstat==0.3.3``` doesn't work.  
* Windows 10 64 bit
* pip 20.0.2
* Python 3.8.1
* Pandas 1.0.3

pips logfile is here: [log.txt](https://github.com/Roche/pyreadstat/files/4555119/log.txt)

The trouble seems to start in line 295: ```2020-04-30T00:02:25,498     pyreadstat/pyreadstat.c(672): fatal error C1083: Datei (Include) kann nicht geöffnet werden: "unistd.h": No such file or directory```  
Translated: File (Include) can't be opened.  
The issue seems to be that another file would be needed for windows: https://stackoverflow.com/questions/22705751/cannot-open-include-file-unistd-h-no-such-file-or-directory

Last working version is ```pyreadstat==0.3.2```

## To Reproduce
```pip install pyreadstat==0.3.3```

## Expected behavior
pyreadstat should be installed.

## Setup Information:
* How did you install pyreadstat? (pip, conda, directly from repo): pip  
* Platform (windows, macOS, linux, 32 or 64 bit): Windows 10 64bit  
* Python Version: 3.8.1  
* Python Distribution (System, plain python, Anaconda): System/ Standard Installation  
* Using Virtualenv or condaenv? system environment. I was able to install the version with anacondas standard environment.

**Comment by ofajardo** [comment]
I cannot reproduce the issue, meaning for me it installs fine. 

The first question I have for you is: is it installing the pre-compiled wheel or is trying to compile? because I understand it would ask for a header file during compilation but I don't see why it should ask for it if the wheel is pre-compiled. 

In order to know that: 
* Can you please paste the full output of the console

* Can you please download the wheel from [here](https://files.pythonhosted.org/packages/dd/b4/b241be396463dedfdfdef8935e8f13fea466c3a5e918431c0dbe735110ec/pyreadstat-0.3.3-cp38-cp38-win_amd64.whl) and install with pip (pip install pyreadstat-0.3.3-cp38-cp38-win_amd64.whl). Does it raise the same error? 

* maybe you are using inadvertely python 32 bit? For python 32 bit there is no wheel for python 3.8, it would try to compile and you would see all kind of strange things. SOlution: move to python 64 bit. (in order to know, what does this print in the python console: import struct; print(struct.calcsize('P') * 8)

**Comment by finnkr539** [comment]
Thank you, this worked. The issue was with Python being 32bit. With 64bit now everythings works on my end.
