### ISSUE TITLE
Building with MSVC

### ISSUE THREAD

**Issue by jonathon-love** [Roche/pyreadstat#7]
hi,

i just found your library, and i've done something similar. however, i *do* have a patch for getting readstat to build with MSVC if you want to pillage:

https://github.com/jonathon-love/ReadStat/commit/baba3b998e24b66a19664f151405d68bcb4e75fc

(i went down the same path of trying to get it to build with mingw, but gave up :P)

jonathon

**Comment by jonathon-love** [comment]
i haven't been able to get it accepted upstream (https://github.com/WizardMac/ReadStat/issues/131)

**Comment by ofajardo** [comment]
hey @jonathon-love, thanks a lot for the heads up!

Very nice design the one of jamovi-readstat, very flexible!. I am also amazed on how you managed to make Readstat to compile with MSVC (it does compile and work correctly in my hands by the way). 

As mingw is working fine for me at the moment (I have documented it [here](https://github.com/Roche/pyreadstat/blob/master/windows_compilation.md), in case you are curious) I will stick to the main ReadStat trunk for the time being, as I want to be able to take any good change in ReadStat immediately with minimal effort ... using a modified version of ReadStat would require to do some manual merging, which I would like to avoid. 

If in the future you get your changes merged with the main trunk, I will very quickly change my compilation process to MSVC. 

Otherwise, very nice to meet you, let's keep in touch in case we can join efforts for some tasks at some point. And congratulations for Jamovi ... looks like a very nice and promising application!

Otto

**Comment by ofajardo** [comment]
closed after 1 month of inactivity
