### ISSUE TITLE
Writing files

### ISSUE THREAD

**Issue by jttaggart** [Roche/pyreadstat#97]
Please read the README, particularly the known limitations section!

I'm writing files to files to SPSS (.sav)

The file is saving OK but there are no labels.

I read .sav file with:
dfMain, meta = pyreadstat.read_sav(read_savFile, usecols=allList, user_missing=False)

I wrote with:
pyreadstat.write_sav(dfMain, "saved.sav", variable_value_labels=loadDict)
Value labels are updated as expected from loadDict but all Labels are blank.

The following didn't write Labels or Value labels
pyreadstat.write_sav(dfMain, "saved.sav")

File example
Please include an example file. If we are not able to reproduce the issue, we cannot fix it!

Expected behavior
I thought the meta data files when read would be the defaults when writing.

I'm using SPSS 26.0

Setup Information:
How did you install pyreadstat? (pip, conda, directly from repo)
From within PyCharm
Platform (windows, macOS, linux, 32 or 64 bit)
Windows 10 Pro
Python Version
3.7
Python Distribution (System, plain python, Anaconda)

Using Virtualenv or condaenv?

**Comment by ofajardo** [comment]
That's a SPSS question, not a pyreadstat issue. In SPSS you have to toggle the value labels to make them visible:
https://ezspss.com/display-value-labels-in-spss/

If the issue is something else, then please as indicated in the issue template provide means to reproduce it: a sample file, the code you are using, and how you are assessing the issue is there.
